### ISSUE TITLE
Add firebase details in a seperate env file

### ISSUE THREAD

**Issue by Aryangp** [Aryangp/Ethflix-aryan-gp#1]
Currently, the Firebase configuration information is stored directly in the application code. To enhance security and flexibility, we should create an environment (env) file and store this sensitive data there. This approach not only improves the security of our application but also makes it more adaptable and dynamic

**Comment by Yogeshp0012** [comment]
Please assign me this issue.

**Comment by Aryangp** [comment]
Sure @Yogeshp0012
